version: '3.8'

services:

  app:
    image: dialloousmane1999/amicale-chicory:latest
    container_name: laravel_app
    working_dir: /var/www
    depends_on:
      - db

  webserver:
    image: dialloousmane1999/amicale-nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: amicale
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3304:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

